server:
  port: 5555

  #Setting logging levels
logging:
    level:
      com.netflix: WARN
      org.springframework.web: WARN
      com.thoughtmechanix: DEBUG

eureka:
  instance:
    hostname: 51.141.9.85
    preferIpAddress: false
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
        defaultZone: http://51.141.9.85:8761/eureka/

#
#
#  debug:
#    request: true
#

zuul:
  prefix:  /api
  routes:
    organizationservice: /organization/**
    licensingservice: /licensing/**
    microservice-mysql-simple: /**
    my-patient-microservice: /**
    #microservice-mysql-simple: /microservice-mysql-simple/**
    #my-patient-microservice: /my-patient-microservice/**
    